name    'palli-createrepo'
version '0.9.6'
source 'https://github.com/pall-valmundsson/puppet-createrepo.git'
author 'Pall Valmundsson'
license 'GPLv3'
summary 'Manages creation of yum repositories'
description 'Creates yum repositories and installs cron jobs to update metadata.'
project_page 'https://github.com/pall-valmundsson/puppet-createrepo'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
